---
- name: copy postgres consul check
  template:
    dest: "/usr/local/bin/postgresql.py"
    owner: "root"
    group: "root"
    mode: 0755
    src: "templates/postgresql.py.j2"
  become: true
  register: result

- name: install pip
  apt:
    name: python-pip
    state: present
  become: true

- name: install python-consul module
  pip:
    name: python-consul
    version: 0.7.2
    state: present
  become: true

- name: register postgresql in consul
  consul:
    token: "{{ ansible_consul_token }}"
    host: "{{ ansible_all_ipv4_addresses[0] }}"
    service_name: app-postgres
    service_port: 6432
    interval: 2s
    script: /usr/local/bin/postgresql.py master
    state: present
#  when: result|changed

- name: register postgresql ro in consul
  consul:
    token: "{{ ansible_consul_token }}"
    host: "{{ ansible_all_ipv4_addresses[0] }}"
    service_name: app-postgres-ro
    service_port: 6432
    interval: 2s
    script: /usr/local/bin/postgresql.py slave
    state: present
#  when: result|changed
