---
- name: install pip
  apt:
    name: python-pip
    state: present
  become: true

- name: install python-consul module
  pip:
    name: python-consul
    version: 1.1.0
    state: present
  become: true

- name: register logstash in consul
  consul:
    token: "{{ ansible_consul_token }}"
    host: "{{ ansible_all_ipv4_addresses[0] }}"
    service_name: app-logstash
    service_port: 10514
    interval: 30s
    http: http://127.0.0.1:8001
    state: present
