---
# Create gitlab database
- name: create gitlab database
  postgresql_db:
    name: "{{ gitlab_k8s_db_dbname }}"
  when: hostvars[inventory_hostname]['repmgr_is_master'] is defined

- name: create gitlab user
  postgresql_user:
    db: "{{ gitlab_k8s_db_dbname }}"
    name: "{{ gitlab_db_username }}"
    password: "{{ gitlab_db_password }}"
  when: hostvars[inventory_hostname]['repmgr_is_master'] is defined

- name: enable pg_trgm
  postgresql_ext:
    name: pg_trgm
    db: "{{ gitlab_k8s_db_dbname }}"
  when: hostvars[inventory_hostname]['repmgr_is_master'] is defined

- name: enable pg_buffercache in postgres database
  postgresql_ext:
    name: pg_buffercache
    db: "postgres"
  when: hostvars[inventory_hostname]['repmgr_is_master'] is defined

- name: enable pg_buffercache in gitlab database
  postgresql_ext:
    name: pg_buffercache
    db: "{{ gitlab_k8s_db_dbname }}"
  when: hostvars[inventory_hostname]['repmgr_is_master'] is defined

- name: enable pg_stat_statements in postgres database
  postgresql_ext:
    name: pg_stat_statements
    db: "postgres"
  when: hostvars[inventory_hostname]['repmgr_is_master'] is defined

- name: enable pg_stat_statements in gitlab database
  postgresql_ext:
    name: pg_stat_statements
    db: "{{ gitlab_k8s_db_dbname }}"
  when: hostvars[inventory_hostname]['repmgr_is_master'] is defined
