---
- name: Ensure local certs directory exists
  file: state=directory path=/usr/local/share/ca-certificates

- name: Install Root CA
  copy:
    src: {{ item }}
    dest: /usr/local/share/ca-certificates/{{ item | basename }}
  with_items:
    - /etc/ansible/files/vault/int_units_cloud/chain.pem 

- name: Update cert index
  shell: /usr/sbin/update-ca-certificates
