---

- name: copy postgres zabbix configuration
  template:
    dest: "/etc/zabbix/zabbix.d/userparameter_postgresql.conf"
    owner: "zabbix"
    group: "zabbix"
    mode: 0755
    src: "files/userparameter_postgresql.conf"
  become: true
  notify: restart zabbix
