---
# Scripts that should be located on the zabbix servers
- name: copy zabbix scripts
  copy:
    dest: "/usr/lib/zabbix/externalscripts/{{ item }}"
    owner: "zabbix"
    group: "zabbix"
    mode: 0755
    src: "files/zabbix/{{ item }}"
  become: true
  with_items:
    - consul.py
    - zbxjson.py
    - zext_ssl_cert.sh
    - elastizabbix

- name: install python-ntlm
  apt: pkg={{ item }} state=present update_cache=yes
  become: true
  with_items:
    - python-ntlm
    - python-docopt
    - python-requests
    - bc


- name: Copy zabbix agent config
  copy:
    dest: "/etc/zabbix/zabbix_agentd.d/{{ item }}"
    owner: "zabbix"
    group: "zabbix"
    mode: 0644
    src: "files/zabbix/{{ item }}"
  become: true
  with_items:
    - elastizabbix.conf
