---

- name: copy postgres zabbix configuration
  copy:
    dest: "/etc/zabbix/zabbix_agentd.d/userparameter_postgresql.conf"
    owner: "zabbix"
    group: "zabbix"
    mode: 0755
    src: "files/userparameter_postgresql.conf"
  become: true
  notify: restart zabbix

- name: create zabbix database
  postgresql_db:
    name: "{{ zabbix_server_dbname }}"
  when: hostvars[inventory_hostname]['repmgr_is_master'] is defined

- name: create zabbix user
  postgresql_user:
    db: "{{ zabbix_server_dbname }}"
    name: "{{ zabbix_server_dbuser }}"
    password: "{{ zabbix_server_dbpassword }}"
  when: hostvars[inventory_hostname]['repmgr_is_master'] is defined

- name: create zabbix grafana user
  postgresql_user:
    db: "{{ zabbix_server_dbname }}"
    name: "{{ zabbix_server_grafanauser }}"
    password: "{{ zabbix_server_grafanapassword }}"
  when: hostvars[inventory_hostname]['repmgr_is_master'] is defined

- name: grant zabbix grafana user select privileges
  postgresql_privs:
    db: "{{ zabbix_server_dbname }}"
    roles: "{{ zabbix_server_grafanauser }}"
    type: database
    state: present
    privs: select

