---

- name: copy postgres zabbix configuration
  copy:
    dest: "/etc/zabbix/zabbix_agentd.d/userparameter_postgresql.conf"
    owner: "zabbix"
    group: "zabbix"
    mode: 0755
    src: "files/userparameter_postgresql.conf"
  become: true
  notify: restart zabbix

- name: create zabbix database
  postgresql_db:
    name: "zabbix"
  when: hostvars[inventory_hostname]['repmgr_is_master'] is defined

- name: create zabbix user
  postgresql_user:
    db: "zabbix"
    name: "zabbix"
  when: hostvars[inventory_hostname]['repmgr_is_master'] is defined
